### ISSUE TITLE
Error: Cannot find module './lib/utils'

### ISSUE THREAD

**Issue by gluons** [gluons/template-gluons#1]
Got error when use it.

```bash
> sao gluons test         
ERROR Error: Cannot find module './lib/utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/illuminator/.nvm/versions/node/v6.10.3/lib/node_modules/template-gluons/sao.js:3:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by gluons** [comment]
Reported to SAO.

egoist/sao#34
